include:
  - project: nse/ci
    file:
      - /ci/jobs/lint.yml
  - project: hpc/gitlab-pipelines
    file:
      - tox-nse-docs.gitlab-ci.yml

variables:
  KUBERNETES_CPU_LIMIT: 4100m
  KUBERNETES_CPU_REQUEST: 4
  KUBERNETES_MEMORY_LIMIT: 8Gi
  KUBERNETES_MEMORY_REQUEST: 8Gi

.tox-template:
  variables:
    SYS_PACKAGES: cmake git java-11-openjdk ninja-build mpich-autoload mpich-devel
    CC: /usr/lib64/mpich/bin/mpicc
    CXX: /usr/lib64/mpich/bin/mpicxx
    PRE_BUILD_COMMAND: "export CC=/usr/lib64/mpich/bin/mpicc CXX=/usr/lib64/mpich/bin/mpicxx"

build-wheels:
  parallel:
    matrix:
      - PY_VERSION: [py311]
