nse_stack:
  stage: test
  trigger:
    include:
      - local: .gitlab-ci.nse.yml
    strategy: depend

hpc_stack:
  stage: test
  trigger:
    include:
      - local: .gitlab-ci.hpc.yml
    strategy: depend
