include:
  - project: nse/ci
    file:
      - /ci/jobs/lint.yml
  - project: hpc/gitlab-pipelines
    file:
      - tox-nse-docs.gitlab-ci.yml

variables:
  KUBERNETES_CPU_LIMIT: 4100m
  KUBERNETES_CPU_REQUEST: 4
  KUBERNETES_MEMORY_LIMIT: 8Gi
  KUBERNETES_MEMORY_REQUEST: 8Gi

.tox-template:
  variables:
    SYS_PACKAGES: cmake git hdf5-devel java-11-openjdk ninja-build
    PRE_BUILD_COMMAND:
      sh .ci/install_morphokit.sh
      &&
      export CMAKE_PREFIX_PATH="$(<morphokit_location.txt):${CMAKE_PREFIX_PATH:+:}${CMAKE_PREFIX_PATH}"

build-wheels:
  parallel:
    matrix:
      - PY_VERSION: [py39, py310]
