#!/usr/bin/env bash
# #############################################################################
# ispyfunc - A script for quick starting an ipython pyspark session with the
#            required libs from pyspark.
#
# Author: Fernando.pereira@epfl.ch
# Copyright (C) 2017 EPFL - Blue Brain Project
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301 USA
# #############################################################################

export PYSPARK_DRIVER_PYTHON_OPTS="--TerminalInteractiveShell.xmode=Plain"
PYSPARK_DRIVER_PYTHON=ipython pyspark --jars java/spykfunc_udfs.jar
